version: "2"
services:
  lambda:
    container_name: lambda 
    build: .
    volumes:
      - "/tmp/lambda-gateway:/tmp"
    environment:
      - "AWS_REGION"
      - "AWS_ACCESS_KEY_ID"
      - "AWS_SECRET_ACCESS_KEY"
  nginx:
    container_name: nginx 
    image: nginx 
    depends_on:
      - "lambda"
    ports:
      - "8080:8080"
    volumes:
      - "/tmp/lambda-gateway:/tmp"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

